# Generated by Django 5.0.7 on 2026-03-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada')], default='ativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
