# Generated by Django 6.0.2 on 2026-03-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0002_compra_status_alter_compra_id_alter_itemcompra_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcompra",
            name="peso_volume",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="itemcompra",
            name="preco_atacado",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="itemcompra",
            name="qtd_min_atacado",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="compra",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="itemcompra",
            name="foto",
            field=models.ImageField(blank=True, upload_to="produtos/"),
        ),
        migrations.AlterField(
            model_name="itemcompra",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
