# Generated by Django 6.0.2 on 2026-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0003_itemcompra_peso_volume_itemcompra_preco_atacado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcompra",
            name="ocr_texto",
            field=models.TextField(blank=True, default=""),
        ),
    ]
