# Generated by Django 6.0.2 on 2026-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0004_add_ocr_texto_to_itemcompra"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="nome",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="compra",
            name="orcamento",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
